### ISSUE TITLE
Is Demo Available?

### ISSUE THREAD

**Issue by ErenBalatkan** [XavierCHEN34/ClickSEG#1]
Greetings,

I see that RITM codebase had an interactive demo where we could evaluate the methods ourselves, but seems to be removed on this branch. Are there any such interactive demo available for FocalClick?

**Comment by XavierCHEN34** [comment]
As we developed another UI system for the internal of our company, we remove the demo provide by ritm.  
You could add them back by yourself referring to the code of ritm, but I think some modifications are required.

**Comment by ErenBalatkan** [comment]
Okay, thanks

**Comment by joshmyersdean** [comment]
With your refinement method would the user have to also supply a crop of the object of interest?
