### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by joshmyersdean** [XavierCHEN34/ClickSEG#11]
Hello, thank you for the work.

What ImageNet weights are you specifically using for pre-training? For W18_S2 I tried a few different weights from the HRNet repo but they did not match.

Thank you!

**Comment by XavierCHEN34** [comment]
Hi, we use HRNet-W18-C-Small-v2 in https://github.com/HRNet/HRNet-Image-Classification

**Comment by joshmyersdean** [comment]
Thank you!
