### ISSUE TITLE
Training sucked from the start, need help

### ISSUE THREAD

**Issue by yangshunDragon** [XavierCHEN34/ClickSEG#2]
Hello, dear author
Thanks for opening source the great project.

I tried to reproduce your algo on my own dataset, while the training sucked from the start with  0%.
I also tried the original coco_lvis dataset, and I got the same error.
![image](https://user-images.githubusercontent.com/5627058/167247226-916dcde2-3862-4d1d-b923-f145c843584c.png)

I used one GPU with enough memory for training, and my pip env list is as below:
Package                 Version
----------------------- ---------------------
absl-py                 1.0.0
addict                  2.4.0
albumentations          0.5.1
attr                    0.3.1
attrs                   21.2.0
backcall                0.2.0
cachetools              5.0.0
certifi                 2021.10.8
charset-normalizer      2.0.12
cycler                  0.11.0
Cython                  0.29.23
decorator               5.1.1
easydict                1.9
google-auth             2.6.5
google-auth-oauthlib    0.4.6
grpcio                  1.44.0
idna                    3.3
imageio                 2.15.0
imgaug                  0.4.0
importlib-metadata      4.11.3
ipython                 7.30.1
jedi                    0.18.1
kiwisolver              1.4.2
Markdown                3.3.6
matplotlib              3.3.4
matplotlib-inline       0.1.3
mmcv                    1.4.1
mmcv-full               1.2.7
networkx                2.8
numpy                   1.17.3
oauthlib                3.2.0
opencv-contrib-python   4.2.0.32
opencv-python           4.5.5.64
opencv-python-headless  4.5.5.64
packaging               21.3
parso                   0.8.3
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  8.4.0
pip                     22.0.4
prompt-toolkit          3.0.29
protobuf                3.20.0
ptyprocess              0.7.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
Pygments                2.11.2
pyparsing               3.0.8
python-dateutil         2.8.2
PyWavelets              1.3.0
PyYAML                  6.0
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-image            0.17.2
scipy                   1.5.4
setuptools              62.1.0
Shapely                 1.8.1.post1
six                     1.16.0
tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               1.1.0
thop                    0.0.31.post2005241907
tifffile                2021.11.2
timm                    0.3.2
torch                   1.7.1
torchaudio              0.8.0
torchvision             0.8.2
tqdm                    4.61.0
traitlets               5.1.1
typing_extensions       4.1.1
urllib3                 1.26.9
wcwidth                 0.2.5
Werkzeug                2.1.1
wheel                   0.37.1
yapf                    0.32.0
zipp                    3.8.0

Could you please give me some tip what is going on?

Thanks in advance!

**Comment by XavierCHEN34** [comment]
I suggest you to interrupt the  algorithm , then you could read the error log  in the command line to see where  it  actually stuck. 
I guess you meet something wrong when loading the data.  You could remove the  "try" and "except"  in the line37 and line119 of https://github.com/XavierCHEN34/ClickSEG/blob/main/isegm/data/base.py.  Then, there would be log errors
