### ISSUE TITLE
Inference case for real use cases

### ISSUE THREAD

**Issue by HenryKang1** [XavierCHEN34/ClickSEG#3]
Hello. thank you for sharing the code. I have question about inference of single image.
In the evaluation.py 
You use the "for loop"
 for click_indx in range(max_clicks):
However in the real world, there is no ground truth. I can remove the for loop and give the coordinate positive and negative however i am quite not sure, How we can update the previous information not only the mask, but also the previous click. Do you just keep stacking the mouse click list like below
{  'pclicks' : [],     'nclicks' : []}
I am wondering how you can use the previous click properly.
Thank you.

**Comment by XavierCHEN34** [comment]
In real world applications,  users also place clicks iteratively in many rounds. The final input for the model is "two click maps(positive and negative click map) for all clicks,  the previous mask, and  the last click coordinations".
Hence,  as you said, "directly stacking historical clicks" is OK.

**Comment by HenryKang1** [comment]
Thank you for answering. Does your code consider the previous history of click? when the setting becomes the focal click?
Thank you.

**Comment by XavierCHEN34** [comment]
All settings would consider the historical clicks, but do not consider their order

**Comment by HenryKang1** [comment]
Thanks
