### ISSUE TITLE
Industrial data

### ISSUE THREAD

**Issue by Ehteshamciitwah** [XavierCHEN34/ClickSEG#4]
Hello, Congratulations on your wonderful work. Before proceeding to the implementation part I just to clarify few things

1.  Can we train your model on industrial data to get industrial image annotation
2. What is the performance of your model on cross-domain.(pretrained on real world data .. test on industry data or vice versa).
3. what is inference time according to image size.
 Thank you .

**Comment by XavierCHEN34** [comment]
Hi, what does "industrial data" mean?
1. Anyway, if you have training samples, I think our model would work after fine-tuning.
2. I do not know what is "industry data". If the domain gap is big, i think finetuning is required. 
4. During inference, we resize the image into fixed sizes like 256x256, 448x448, etc.  Some inference times are reported in the paper of FocalClick. Other inference times should be tested by yourself.
