### ISSUE TITLE
Missing results for models trained on SBD

### ISSUE THREAD

**Issue by qinliuliuqin** [XavierCHEN34/ClickSEG#8]
Dear authors, 

Thanks for your great work! It's very inspiring!
I am currently comparing with SOTA interactive image segmentation methods. Could you let me know where can I get the missing entries in the following table? 
![image](https://user-images.githubusercontent.com/57234075/192115821-7820c8d0-78d5-4dc4-89c1-56ad15c65fb1.png)
Thank you in advance!

Best,
Qin

**Comment by XavierCHEN34** [comment]
Sorry that we do not have the time and resources to train it. If you are interested, you could train it by yourself using our codebase.

**Comment by qinliuliuqin** [comment]
Thanks for your kind reply!
Yes, I just wanted to know if you happened to record those missing numbers before retraining.
Thanks for letting us know. We are planning to retrain the SBD models once we get time.
